services:
  db_dhis2_esavi:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dhi_esavi
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    