###
# Ejemplos de consumo para el servicio de Vacunación Nominal
# API: VacunacionNominalService
# Controlador: VacunacionNominalSyncController
###

# Variables de configuración
@host = http://localhost:8081
@api_version = v1
@api_key = tu-api-key-aqui

### 1. Sincronizar vacunas agregadas para una fecha específica
# Procesa las vacunas aplicadas en una fecha determinada y las agrega al vacunómetro
GET {{host}}/vacunacion-nominal-sync/sync?fecha=2025-01-01
X-API-KEY: {{api_key}}
Content-Type: application/json

### 1. Sincronizar vacunas agregadas para una fecha específica
# Procesa las vacunas aplicadas en una fecha determinada y las agrega al vacunómetro
GET {{host}}/vacunacion-nominal-sync/count
X-API-KEY: {{api_key}}
Content-Type: application/json

