export {
  IDrug,
  IDrugPaginated,
  IDrugResponse,
  IDrugProcces,
  ICountryOfSale,
  IMaHolder,
  IActiveIngredient,
  IIngredientTranslation,
  IATC,
  IWhodrugVaccineMatch,
  ICodificacionVacunaWhodrug,
  ICodificacionVacunaWhodrugConDrugId,
  ICodificacionVacunaWhodrugDetallada,
} from './drug.dto';
