### Obtener JWT
GET http://localhost:8081/integrator/vigiflow/retrieveJWT
Content-Type: application/json

###

### Descargar archivo Excel
GET http://localhost:8081/integrator/vigiflow/download
Content-Type: application/json

# Parámetros de consulta
# Reemplaza los valores según sea necesario
?fechaInicio=20230101&fechaFin=20230131&codigoATC=A01

###

### Importar datos en bloque
GET http://localhost:8081/integrator/vigiflow/bulk
Content-Type: application/json

# Parámetros de consulta
# Reemplaza los valores según sea necesario
?fechaInicio=20230101&fechaFin=20230131&codigoATC=A01



### Retrieve JWT
GET http://localhost:3000/integrator/vigiflow/retrieveJWT
X-API-KEY: your-api-key-here

###

### Download Excel File
GET http://localhost:8081/integrator/vigiflow/download?fechaInicio=20250802&fechaFin=20250806&codigoATC=J07
X-API-KEY: '6PxFc1GiLz8i2EWuJkj9qrJOrqjTNW4h'
###X-API-KEY: your-api-key-here
### Codificación de la URL en el valor se "codigoATC" A2:AS2990, los dos puntos deben ser codificados como %3A
### el valor de "codigoATC" es el rango de las celdas o registros que se desean descargar, en este caso A2 hasta AS2990 del documento de Excel.
### GET http://localhost:8081/integrator/vigiflow/download?fechaInicio=20250701&fechaFin=20250731&codigoATC=A2%3AAS2990

###

### Bulk Import
GET http://localhost:8081/integrator/vigiflow/bulk?fechaInicio=20250802&fechaFin=20250806&codigoATC=J07
X-API-KEY: your-api-key-here