const ENV_CONFIG = {
  INT_ESAV_API: import.meta.env.REACT_APP_INTEGRA_ESAVI_API_URL,
  INT_API_KEY: import.meta.env.REACT_APP_API_KEY,
  INT_KEYCLOAK_URL: import.meta.env.REACT_APP_KEYCLOAK_URL,
  INT_KEYCLOAK_REALM: import.meta.env.REACT_APP_KEYCLOAK_REALM,
  INT_KEYCLOAK_CLIENT_ID: import.meta.env.REACT_APP_KEYCLOAK_CLIENT_ID,
}

export default ENV_CONFIG
