const ENV_CONFIG = {
  INT_ESAV_API: import.meta.env.VITE_INTEGRA_ESAVI_API_URL,
  INT_API_KEY: import.meta.env.VITE_APP_API_KEY,
  INT_KEYCLOAK_URL: import.meta.env.VITE_KEYCLOAK_URL,
  INT_KEYCLOAK_REALM: import.meta.env.VITE_KEYCLOAK_REALM,
  INT_KEYCLOAK_CLIENT_ID: import.meta.env.VITE_KEYCLOAK_CLIENT_ID,
  INT_ESAVI_DASHBOARD_TOKEN: import.meta.env.VITE_ESAVI_DASHBOARD_TOKEN,
}

export default ENV_CONFIG
